language: cpp

compiler:
  - clang

before_script:
  - mkdir build
  - cd build
  - cmake ..

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev libsqlite3-dev

script: make
